### ISSUE TITLE
Move from launchpad.net/goyaml to "gopkg.in/yaml.v2"

### ISSUE THREAD

**Issue by nizsheanez** [manveru/faker#5]
there problems with launchpad.net:

glide shows this:
```
Skipped getting launchpad.net/goyaml: Not checking SSL certificate for launchpad.net.
bzr: ERROR: Parent of "vendor/launchpad.net/goyaml" does not exist.
: exit status 3
```

**Comment by manveru** [comment]
There are more problems than that with the importer. I'll probably have to rewrite it because the YAML format of the faker gem changed again.

**Comment by AlekSi** [comment]
Related: ceb0b08ac7c0d4b9afee5fd22800fffbba52d578

**Comment by dencold** [comment]
I have updated the import path, see #8, this should fully close out this issue. Thanks again @AlekSi!
